name: .NET Build and Pack

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      run: dotnet build SpectrumAnalyzerPlus.csproj --configuration Release
      working-directory: ${{ github.workspace }}
    - name: Run unit tests
      run: dotnet test --configuration Release
      working-directory: ${{ github.workspace }}
    - name: Generate nuget package
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ${{ github.workspace }}
    - name: Push nuget package
      run: dotnet nuget push **/*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.CHROMATICITYDOTNETAPI}} --skip-duplicate
      working-directory: ${{ github.workspace }}
